[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"  # Frontend requests to /api
  to = "https://be2003.netlify.app/.netlify/functions/api/:splat"  # Your backend function URL
  status = 200  # Make sure it's a rewrite (not redirect)
  force = true

[[headers]]
  for = "/api/*"  # Apply headers for this proxy route
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Allow all origins (or limit to your frontend domain)
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
