[build]

    functions = "functions"

[[redirects]]
  from = "/api"  # Path you will use in frontend (e.g., /api will be mapped to external API)
  to = "https://be2003.netlify.app/.netlify/functions/api"  # Your actual API URL
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/api/*"  # Make sure this matches the proxy route above
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Allow any origin
