[build]
  functions = "functions"

[[redirects]]
  from = "/api"
  to = "https://be2003.netlify.app/.netlify/functions/api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Allow any origin (you could specify a specific origin if needed)
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
